#!/bin/sh
#
# @name Generic Surface Robot
#
# @type Surface Robot
# @class Surface Robot
#
# @maintainer Daniel Williams <equipoise@gmail.com>
#
# see also: ROMFS/px4fmu_common/init.d-posix/airframes/1070_boat

. ${R}etc/init.d/rc.usv_defaults


#Set data link loss failsafe mode (0: disabled)
param set-default NAV_DLL_ACT 0

# disable circuit breaker for airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

set MAV_TYPE 11
param set MAV_TYPE ${MAV_TYPE}

set MIXER boat

# # copied from:
#    `ROMFS/px4fmu_common/init.d-posix/airframes/1070_boat`
#
# param set-default GND_L1_DIST 5
# param set-default GND_L1_PERIOD 100
# param set-default GND_SP_CTRL_MODE 1
# param set-default GND_SPEED_D 0.001
# param set-default GND_SPEED_I 8
# param set-default GND_SPEED_IMAX 0.125
# param set-default GND_SPEED_P 2
# param set-default GND_SPEED_THR_SC 1
# param set-default GND_SPEED_TRIM 1
# param set-default GND_THR_CRUISE 0.85
# param set-default GND_THR_MAX 1
# param set-default GND_THR_MIN 0
#
# param set-default MIS_LTRMIN_ALT 0.01
# param set-default MIS_TAKEOFF_ALT 0.01
# param set-default NAV_ACC_RAD 0.5
# param set-default NAV_LOITER_RAD 2
#
# param set-default CBRK_AIRSPD_CHK 162128
#
# param set-default GND_MAX_ANG 0.6
# param set-default GND_WHEEL_BASE 2.0
